### ISSUE TITLE
Unable to develop in the latest version 

### ISSUE THREAD

**Issue by srihari1988** [koltyakov/sp-rest-proxy#20]
Hi,

I would like to start with thanking you for this amazing work which has eased in my development. 

Coming to the issue, I was previously using version 1.2 (guessing as I deleted older version) and upgraded to the latest version following the steps in the documentation. However, I get an error stating "Cannot find module 'dist\server'. 

Error screenshot is attached. Please help. 

![sp-rest-proxy error](https://user-images.githubusercontent.com/8217857/27605266-020a4016-5b31-11e7-944c-1c922afe09b5.PNG)

**Comment by koltyakov** [comment]
Hi Srihari,

Thank you for using the lib and posting this.
For me, it compiles without semantic errors (tsc, Version 2.3.4), which are not critical, btw. 

Is there `./dist/server/index.js` or `./dist/server.js` in your project?
If it's a clone version there will be no such files. That's why node says 'cannot find module'.

Are there any reasons in cloning the project and running th eproxy with `gulp tsc && node ./dist/server` instead of using `sp-rest-proxy` as a drop in library?

Please check a mininal setup project usage for sp-rest-proxy [example](https://github.com/koltyakov/sp-rest-proxy/tree/master/examples/simpleserver). There is no need to clone and transpile typescript version for local development purpuses with library.

**Comment by srihari1988** [comment]
Hi Koltyakov,

I am developing a local Angular application which uses SharePoint REST APIs. This library helps me to avoid the CORS issue and continue my development (Production URLs will be directly calling SharePoint). That's the reason I am cloning the project to run a local proxy server.

Yes, I do not have ./dist/server/index.js or ./dist/server.js in my project as I just cloned the repository. Do I just have to create a server.js file and use the configuration? I am a newbie to NPM, so your directions are much appreciated.

**Comment by srihari1988** [comment]
Hi Koltyakov,

I just checked the example that you posted in previous comment and also the documentation for it, which is very simple. I did test running it and it works as expected. Thank you so much for the wonderful work.

**Comment by koltyakov** [comment]
Sweet. Glad to here you figured it out.
Closing the issue. Happy sp proxying! 

--
Cheers,
Andrew
