### ISSUE TITLE
Add a warning if HTTP_PROXY/HTTPS_PROXY env var is set

### ISSUE THREAD

**Issue by fowl2** [koltyakov/sp-rest-proxy#53]
or otherwise connection to target times out.

Took me a while to figure out why everything was returning 500s. :)

**Comment by koltyakov** [comment]
Hey James @fowl2!

Could you please describe desired logic?

I have some concerns that checking `process.env.HTTP_PROXY || process.env.HTTPS_PROXY` and alerting should be a part of the tool. Folks who use network configuration with a proxy for reasons might not need such a message. I consider these settings to be independent from the library. I.e. one can add a message to the initiation script if a team environment has to be configured to use or not to use network proxy settings (like [this](https://github.com/koltyakov/sp-rest-proxy/blob/dev/src/server.ts#L10)):

```typescript
if (process.env.HTTP_PROXY || process.env.HTTPS_PROXY) {
  console.log('Your Node.js environment is configured to use a network proxy.');
}
```

Also, it can be a confusion between HTTP(S)_PROXY and sp-rest-proxy itself.

Are you aware of any best practices related this?

**Comment by fowl2** [comment]
Yeah it's confusing with so many "proxy"s floating around! Thanks for the tool btw :)

My scenario is developing against a local sharepoint instance on a network with corporate proxy to access the internet.  When I forget to unset the proxy env vars, I can't connect to Sharepoint because it's not internet accessible.

`sp-rest-proxy` returns a HTTP 500 with the non-json/plain text body like ` Error: tunneling socket could not be established, statusCode=400` (bad dns?) or `Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 3128 3128:80`.

Perhaps it would better if `sp-rest-proxy` could print something whenever it returned 500?

**Comment by koltyakov** [comment]
How about configuring local environment with `NO_PROXY="*.yourportal.com,another.com"`? To exclude tries of reaching SharePoint via the internet (network proxy)?

> sp-rest-proxy returns a HTTP 500 with the non-json/plain text body like Error: tunneling socket could not be established, statusCode=400 (bad dns?) or Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 3128 3128:80 but the console only shows the request.

I'll check such or similar scenario messaging. Each route has error messages in catches, error messages are sent to the client and on the client (localhost browser page) should be available as usual. I was sure that in a situation that you are experiencing when SP is not accessible, in the network tab where will be a corresponding error message. At the same time in `sp-rest-proxy` console output, I'm not logging these errors as they just routed to the client. In most cases, this is an expected behavior. Will think out this case anyway.

**Comment by fowl2** [comment]
ahah! I didn't know about `NO_PROXY`, better to fix the issue system-wide than just here. 

Thanks for your help again.

And yes, the errors do appear in the Network tab.
