### ISSUE TITLE
Proxy SOAP Requests?

### ISSUE THREAD

**Issue by scatcher** [koltyakov/sp-rest-proxy#6]
Any chance of supporting SOAP requests?  

It would be nice to be able to rely purely on REST but unfortunately I still find myself posting to the SOAP web services pretty frequently.  I'm looking to add that functionality but would appreciate any input you had before I invest too much time.

Thanks again for the work you've done on this project.

--Scott

**Comment by koltyakov** [comment]
Hi Scott,

I didn't plan to add any legacy communications layers as SOAP is to sp-rest-proxy but only REST.
Frankly speaking, the library initially was just a "one-night-coding" experiment to assure in the fact that guys from SPFx team could easily add some similar way into their Workbench to let debug and testing with live data. Yet, they use another also working but less advanced alternative referencing local scripts in debug runtime (published to SP).

In the case of SOAP "wrapper" I can see some challenges, as it can't be as universal as REST, at least it seems to me so, also I can't remember then I needed SOAP in SharePoint.
Did you try "proxying" some specific service operations which you miss with the use of [node-soap](https://github.com/vpulim/node-soap) for example?

Could you please describe your use case for sp-rest-proxy? Very interesting to know.

--
Andrew

**Comment by koltyakov** [comment]
Have some ideas about that. Maybe, will elaborate over the weekend.

**Comment by scatcher** [comment]
Hey Andrew,
I unfortunately still support several 2010 systems with large Angular 1 applications so SOAP is a burden I bear ;)

I spent several hours yesterday trying to add this functionality but I couldn't get the preflight to authenticate with the remote server (Azure).  I can hit the rest endpoints without issue using your existing implementation.  I think the area that's tripping me up is how to pass authentication when posting to the SOAP web services.  Let me know if you have any ideas.

Thanks,
--Scott

**Comment by koltyakov** [comment]
Hi there @scatcher,

It's a bit insane, but I was managed to add some basic proxying for SOAP requests.

Check it out:

![SoapProxy](http://koltyakov.ru/images/SoapProxy.jpg)

What is on background and some limitations are:

- Requests to _vti_bin/* are forwarded to apiSoapRouter method
- Post body is grabbed from the request as a soapBody
- Some magic is happening to the headers for Cookie to contain the authentication keys
- I've been testing this with SPO and only basic SOAP calls like:
   - Get Current Web with SPServices
   - Or get list items with jQuery ajax:
```javascript
$.ajax({
    url: "/_vti_bin/Lists.asmx",
    type: "POST",
    data: "<soap:Envelope xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xmlns:xsd='http://www.w3.org/2001/XMLSchema' xmlns:soap='http://schemas.xmlsoap.org/soap/envelope/'><soap:Body><GetListItems xmlns='http://schemas.microsoft.com/sharepoint/soap/'><listName>test</listName><viewName></viewName><query></query><viewFields><ViewFields><FieldRef Name='Title' /></ViewFields></viewFields><rowLimit>0</rowLimit><queryOptions><QueryOptions></QueryOptions></queryOptions></GetListItems></soap:Body></soap:Envelope>",
    dataType: "xml",
    contentType: "text/xml;charset=\"utf-8\"",
    complete: function (xData) {
        console.log(xData.responseText);
    }
});
```
- SPServices are there on the page just because it was so far ago then I actually used any SOAP requests in SharePoint and I was lazy enough just to extract some soap bodies and endpoints from SPServices =), but SPServices will not work because it's too robust to change URI with actual SP web URLs
- Unfortunately, this will not help you much with SharePoint 2010 because the way auth works. `sp-rest-proxy` totally relies on `node-sp-auth` to deal with SPO, SP2013 and SP2016 with different auth mechanisms 

I'm closing this issue, as SP 2010 is out of the scope of my professional interests. But, maybe, will experiment a bit with auth to SP2010, but do not promise anything.

**Comment by scatcher** [comment]
Once again, really appreciate the work you've done and taking the time to respond.  

I'm very familiar with SPServices and actually use pieces of that code it in my own codebase.  I don't use the full plugin because I needed a bit more customization and don't want to rely on jQuery.

I have a 2013 dev environment on Azure so I'll give it a try.  

Would you mind publishing your latest version to NPM?

Thanks,
--Scott

**Comment by koltyakov** [comment]
Oh, I was sure that I had published it. Weird. Now it's published for sure.
