### ISSUE TITLE
Receiving 404 when trying to Post

### ISSUE THREAD

**Issue by DrakeAnglin** [koltyakov/sp-rest-proxy#99]
Getting data works fine, but I am unable to make any Post requests. We have a SharePoint 2010 on prem server and I have validated that the URL is correct by using postman to successfully post data, and when the app is deployed to the site it also works. I am using version 2.11

GET:
![image](https://user-images.githubusercontent.com/37958526/79622696-482d8e80-80e6-11ea-8c40-89851a8a7644.png)

POST:
![image](https://user-images.githubusercontent.com/37958526/79622711-58456e00-80e6-11ea-9a30-9e56b17967b5.png)

**Comment by DrakeAnglin** [comment]
Did a bit more digging. The issue seams to be [here](https://github.com/koltyakov/sp-rest-proxy/blob/master/src/core/routers/genericPost.ts#L49). 

We are not required to pass the 'X-RequestDigest' header with our on prem solution (not sure why). Since the header is not present, it tries to get the digest, but it's trying to get the digest from "_api" using the requestDigest function which is a SP2013+ api and not an SP2010 api, therefore returns the 404 error.

I think this could be fixed by having a require digest boolean that you could pass in via the config.

**Comment by DrakeAnglin** [comment]
I confirmed that this is in fact the issue by passing in a fake 'X-RequestDigest' header and the proxy worked.

**Comment by koltyakov** [comment]
Glad you've figured out.

Yes, the main use case of the library is SPO/2019/16/13. SP2010 has limited support and never tested together, but just a basic auth capabilities and maybe CSOM.

SP2010 is way too old, I'd say we, as a company, have been declined any SP2010 project since around 2015, so we've never applied proxy with 2010.

The proxy is also designed for REST API (that which appeared in SP2013), then CSOM, custom services, SOAP and assets were also added.

`X-RequestDigest` digest is required for many SP REST POST methods (not each but many), it was a design decision (controversial a bit I would say but it's there) to check and inject `X-RequestDigest` if missed.

Faking the digest for SP2010 is totally fine approach. I'd suggested the same if were reading your post before you came with a solution bu yourself.

I was thinking of removing digest injection for different reasons, by the way. As the perfect situation is to have the same requirements for the code on SP hosted and locally hosted pages. I'd suggest that 70% of the users who use proxy also use PnPjs, which also check and inject the digests for the posts so they are actually never faces than with proxy a request work but fails after a deployment to SharePoint.
